# CatBoost

CatBoost is a gradient boosting algorithm based on decision trees. Due to several differences in its API and data handling compared to previous models, all CatBoost experiments are performed in a separate notebook.

One of the main advantages of CatBoost is its native support for categorical features, eliminating the need for additional preeprocessing techniques such as One-Hot-Encoding. This results in a cleaner and more compact training pipeline while preserving the original categorical information.

This notebook is dedicated exclusively to the CatBoost algorithm. Throughout the following sections, we will establish a baseline model, optimize its hyperparameters using Optuna and evaluate the impact of additional features, including amenities and description embeddings, on the overall prediction performance.

In [1]:
%load_ext autoreload
%autoreload 2

from time import perf_counter

NOTEBOOK_START = perf_counter()

import pandas as pd
import numpy as np
import sys
from pathlib import Path
import seaborn as sns
import matplotlib.pyplot as plt
import catboost
import sklearn

pd.set_option("display.max_columns", 500)

sys.path.append(str(Path().cwd().parent.resolve()))

import preprocessing.features as features

builder = features.FeatureBuilder()

df = pd.read_csv(features.DATASET_PATH)

catboost.__version__

/home/carl/notebooks/airbnb_prices_prediction/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

'1.2.10'

In [2]:
ARTIFACTS_DIR = Path("../artifacts")
ARTIFACTS_DIR.mkdir(exist_ok=True)

TREE_MODELS_RESULTS = ARTIFACTS_DIR / "tree_models_results.csv"

tree_results_df = pd.read_csv(TREE_MODELS_RESULTS, index_col='Model')

tree_results_df.sort_values(by='RMSE', ascending=False)

                                                      MAE    RMSE    R2
Model
RandomForest (baseline, optimized)                  53.55  121.80  0.67
XGBoost (baseline, optimized)                       49.87  113.13  0.71
XGBoost (baseline, optimized, zipcode)              49.36  112.75  0.72
XGBoost (amenities+embeddings, optimized)           48.59  111.36  0.72
XGBoost (am, em (pca_com=370), optimized (alpha...  48.44  111.10  0.73
XGBoost (amenities, embeddings, optimized, zipc...  48.43  111.05  0.73
XGBoost (full df, optimized with alpha)             48.33  110.62  0.73

# CatBoost. Baseline Model

In [3]:
from catboost import Pool, CatBoostRegressor
from catboost.utils import get_gpu_device_count

DEVICE = 'GPU' if get_gpu_device_count() > 0 else 'CPU'
DEVICE

'GPU'

In [4]:
df_copy = builder.get_df(df, use_amenities=False, use_embeddings=False)

df_copy.shape

(74111, 27)

In [5]:
X = df_copy.drop(columns='log_price')
y = df_copy['log_price']

X = X.drop(columns=['zipcode'])

X.shape, y.shape

((74111, 25), (74111,))

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    random_state=42,
    test_size=0.2
)

X_train.shape, X_test.shape

((59288, 25), (14823, 25))

In [7]:
%%time

from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score

cat_features = X_train.select_dtypes(include=['object', 'string']).columns.tolist()

train_pool = Pool(X_train, label=y_train, cat_features=cat_features)
test_pool = Pool(X_test, label=y_test, cat_features=cat_features)

catboost_baseline = CatBoostRegressor(
    loss_function="RMSE",
    eval_metric="RMSE",
    task_type=DEVICE,
    random_seed=42,
    verbose=False
)

catboost_baseline.fit(train_pool)

y_pred_test_log = catboost_baseline.predict(test_pool)
y_pred_train_log = catboost_baseline.predict(train_pool)

y_pred_test = np.exp(y_pred_test_log)
y_pred_train = np.exp(y_pred_train_log)

test_MAE = mean_absolute_error(np.exp(y_test), y_pred_test)
train_MAE = mean_absolute_error(np.exp(y_train), y_pred_train)

test_RMSE = root_mean_squared_error(np.exp(y_test), y_pred_test)
train_RMSE = root_mean_squared_error(np.exp(y_train), y_pred_train)

test_r2 = r2_score(y_test, y_pred_test_log)
train_r2 = r2_score(y_train, y_pred_train_log)

print(f"Test MAE: {test_MAE:.2f}$ | Train MAE: {train_MAE:.2f}$")
print(f"Test RMSE: {test_RMSE:.2f}$ | Train RMSE: {train_RMSE:.2f}$")
print(f"Test R2 Score: {test_r2:.2f} | Train R2 Score: {train_r2:.2f}")

Test MAE: 50.28$ | Train MAE: 46.86$
Test RMSE: 113.50$ | Train RMSE: 103.42$
Test R2 Score: 0.71 | Train R2 Score: 0.74
CPU times: user 10.1 s, sys: 1.57 s, total: 11.6 s
Wall time: 7.55 s

In [8]:
catboost_results_df = pd.DataFrame(columns=[
    "MAE", "RMSE", "R2"
])

catboost_results_df.loc['CatBoost baseline'] = [
    round(test_MAE, 2),
    round(test_RMSE, 2),
    round(test_r2, 2)
]

catboost_results_df

                     MAE   RMSE    R2
CatBoost baseline  50.28  113.5  0.71

In [9]:
tree_results_df.sort_values(by='RMSE', ascending=False)

                                                      MAE    RMSE    R2
Model
RandomForest (baseline, optimized)                  53.55  121.80  0.67
XGBoost (baseline, optimized)                       49.87  113.13  0.71
XGBoost (baseline, optimized, zipcode)              49.36  112.75  0.72
XGBoost (amenities+embeddings, optimized)           48.59  111.36  0.72
XGBoost (am, em (pca_com=370), optimized (alpha...  48.44  111.10  0.73
XGBoost (amenities, embeddings, optimized, zipc...  48.43  111.05  0.73
XGBoost (full df, optimized with alpha)             48.33  110.62  0.73

In [10]:
catboost_baseline.get_all_params()

{'nan_mode': 'Min',
 'gpu_ram_part': 0.95,
 'eval_metric': 'RMSE',
 'combinations_ctr': ['Borders:CtrBorderCount=15:CtrBorderType=Uniform:TargetBorderCount=1:TargetBorderType=MinEntropy:Prior=0/1:Prior=0.5/1:Prior=1/1',
  'FeatureFreq:CtrBorderCount=15:CtrBorderType=Median:Prior=0/1'],
 'iterations': 1000,
 'fold_permutation_block': 64,
 'leaf_estimation_method': 'Newton',
 'observations_to_bootstrap': 'TestOnly',
 'random_score_type': 'NormalWithModelSizeDecrease',
 'counter_calc_method': 'SkipTest',
 'grow_policy': 'SymmetricTree',
 'penalties_coefficient': 1,
 'boosting_type': 'Plain',
 'ctr_history_unit': 'Sample',
 'feature_border_type': 'GreedyLogSum',
 'bayesian_matrix_reg': 0.10000000149011612,
 'one_hot_max_size': 2,
 'devices': '-1',
 'eval_fraction': 0,
 'pinned_memory_bytes': '104857600',
 'force_unit_auto_pair_weights': False,
 'l2_leaf_reg': 3,
 'random_strength': 1,
 'rsm': 1,
 'boost_from_average': True,
 'gpu_cat_features_storage': 'GpuRam',
 'fold_size_loss_normalization': False,
 'max_ctr_complexity': 4,
 'model_size_reg': 0.5,
 'simple_ctr': ['Borders:CtrBorderCount=15:CtrBorderType=Uniform:TargetBorderCount=1:TargetBorderType=MinEntropy:Prior=0/1:Prior=0.5/1:Prior=1/1',
  'FeatureFreq:CtrBorderCount=15:CtrBorderType=MinEntropy:Prior=0/1'],
 'pool_metainfo_options': {'tags': {}},
 'use_best_model': False,
 'meta_l2_frequency': 0,
 'random_seed': 42,
 'depth': 6,
 'ctr_target_border_count': 1,
 'has_time': False,
 'border_count': 128,
 'min_fold_size': 100,
 'data_partition': 'FeatureParallel',
 'bagging_temperature': 1,
 'classes_count': 0,
 'auto_class_weights': 'None',
 'leaf_estimation_backtracking': 'AnyImprovement',
 'best_model_min_trees': 1,
 'min_data_in_leaf': 1,
 'add_ridge_penalty_to_loss_function': False,
 'loss_function': 'RMSE',
 'learning_rate': 0.06895600259304047,
 'meta_l2_exponent': 1,
 'score_function': 'Cosine',
 'task_type': 'GPU',
 'leaf_estimation_iterations': 1,
 'bootstrap_type': 'Bayesian',
 'max_leaves': 64,
 'permutation_count': 4}

## CatBoost. Baseline Model Conclusion

The baseline model achieved strong performance without hypyerparameter optimization. Compared to the optimized Random Forest baseline, CatBoost provides a noticeable improvement in all evaluation metrics while remaining highly competitive with the optimized XGBoost baseline.

Another important observation is relativelt small gap between the training and test metrics, indicating that the default CatBoost model generalizes and and does not exhibit significant overfitting. 

The next step is to optimize the CatBoost hyperparameters using Optuna. The goal is to determine whether additional tuning can further improve the baseline performance before intoducing the full feature set.

# CatBoost. Baseline Model Optimized.

The initial Optuna research space was revised several times due to unstable validatioin metrics and long training times. Numerous exploratory experiments were conducted during development, but they are intentionally ommited from the final notebook because they mainly consisted of temporary debugging code and intermediate tests.

These experiments suggested that using a very broad hyperparameter search space from the begging was not the most effective strategy for CatBoost. At the same time, the baseline CatBoost model, trained with its default configuration, consistently demonstrated strong performance. This indicated that CatBoost's default parameters already provide a solid starting point for the given dataset.

Based on these observations, the optimization strategy was changed. Instead of searching across a wide range of values, the optimized model uses the parameters of the baseline model as a reference point. Narrow search ranges were then defined around these values, allowing Optuna to perform a local hyperparameter search. This approach significantly reduces the search space, focuses the optimization on promising regions and aims to improve the baseline model through fine-tuning rather than searching for an entirely different configuration.

In [11]:
def objective(trial):

    params = {
        "loss_function": "RMSE",
        "eval_metric": "RMSE",
        "task_type": DEVICE,
        "random_seed": 42,
        "verbose": False,

        # Training
        "iterations": 5000,
        "boosting_type": "Plain",

        # Fixed Baseline Parameters
        "bootstrap_type": "Bayesian",
        "bagging_temperature": 1,
        "grow_policy": "SymmetricTree",
        "leaf_estimation_method": "Newton",
        "score_function": "Cosine",
        "border_count": 128,
        "one_hot_max_size": 2,
        "max_ctr_complexity": 4,

        # Hyperparameters to optimize
        "learning_rate": trial.suggest_float("learning_rate", 0.05, 0.09),
        "depth": trial.suggest_int("depth", 5, 8),
        "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 2.0, 6.0),
        "random_strength": trial.suggest_float("random_strength", 0.5, 2.0),
        "min_data_in_leaf": trial.suggest_int("min_data_in_leaf", 1, 5),
    }

    model = CatBoostRegressor(**params)

    model.fit(
        train_pool,
        eval_set=val_pool,
        use_best_model=True,
        early_stopping_rounds=30,
        verbose=False
    )

    rmse = model.get_best_score()['validation']['RMSE']

    return rmse

In [12]:
df_copy = builder.get_df(df, use_amenities=False, use_embeddings=False)

X = df_copy.drop(columns=['log_price'])
y = df_copy['log_price']

X = X.drop(columns=['zipcode'])

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    random_state=42,
    test_size=0.2
)

X_train, X_val, y_train, y_val = train_test_split(
    X_train, y_train,
    random_state=42,
    test_size=0.2
)

X_train.shape, X_val.shape, X_test.shape

((47430, 25), (11858, 25), (14823, 25))

In [13]:
cat_features = X_train.select_dtypes(include=['string', 'object']).columns.tolist()

train_pool = Pool(X_train, label=y_train, cat_features=cat_features)
val_pool = Pool(X_val, label=y_val, cat_features=cat_features)
test_pool = Pool(X_test, label=y_test, cat_features=cat_features)

In [14]:
CATBOOST_DIR = Path('../artifacts/catboost')
CATBOOST_DIR.mkdir(exist_ok=True, parents=True)

CATBOOST_BASELINE = CATBOOST_DIR / "catboost_baseline.cbm"

In [15]:
%%time
import optuna

if CATBOOST_BASELINE.exists():
    print("Loading CatBoost Model...")
    catboost_baseline = CatBoostRegressor()
    catboost_baseline.load_model(CATBOOST_BASELINE)
else:
    print("Training CatBoost Model...")
    optuna.logging.set_verbosity(optuna.logging.WARNING)

    study = optuna.create_study(direction="minimize")

    study.optimize(objective, n_trials=100, gc_after_trial=True)

    best_params = {
        **study.best_params,
    
        "loss_function": "RMSE",
        "eval_metric": "RMSE",
        "task_type": DEVICE,
        "random_seed": 42,
        "verbose": False,
    
        "iterations": 5000,
        "boosting_type": "Plain",
        "bootstrap_type": "Bayesian",
        "grow_policy": "SymmetricTree",
        "leaf_estimation_method": "Newton",
        "score_function": "Cosine",
        "border_count": 128,
        "one_hot_max_size": 2,
        "max_ctr_complexity": 4,
    }

    catboost_baseline = CatBoostRegressor(**best_params)
    catboost_baseline.fit(
        train_pool,
        eval_set=val_pool,
        use_best_model=True,
        early_stopping_rounds=30,
        verbose=False
    )
    catboost_baseline.save_model(CATBOOST_BASELINE)
    
catboost_baseline.get_params()

Training CatBoost Model...
CPU times: user 31min 25s, sys: 4min 9s, total: 35min 34s
Wall time: 24min 35s

{'iterations': 5000,
 'learning_rate': 0.051564043045924525,
 'depth': 8,
 'l2_leaf_reg': 2.0260609915580723,
 'loss_function': 'RMSE',
 'border_count': 128,
 'leaf_estimation_method': 'Newton',
 'random_seed': 42,
 'verbose': False,
 'max_ctr_complexity': 4,
 'one_hot_max_size': 2,
 'random_strength': 1.4715235268043156,
 'eval_metric': 'RMSE',
 'boosting_type': 'Plain',
 'task_type': 'GPU',
 'bootstrap_type': 'Bayesian',
 'grow_policy': 'SymmetricTree',
 'min_data_in_leaf': 3,
 'score_function': 'Cosine'}

In [16]:
y_pred_test_log = catboost_baseline.predict(test_pool)
y_pred_train_log = catboost_baseline.predict(train_pool)

y_pred_test = np.exp(y_pred_test_log)
y_pred_train = np.exp(y_pred_train_log)

test_MAE = mean_absolute_error(np.exp(y_test), y_pred_test)
train_MAE = mean_absolute_error(np.exp(y_train), y_pred_train)

test_RMSE = root_mean_squared_error(np.exp(y_test), y_pred_test)
train_RMSE = root_mean_squared_error(np.exp(y_train), y_pred_train)

test_r2 = r2_score(y_test, y_pred_test_log)
train_r2 = r2_score(y_train, y_pred_train_log)

print(f"Test MAE: {test_MAE:.2f}$ | Train MAE: {train_MAE:.2f}$")
print(f"Test RMSE: {test_RMSE:.2f}$ | Train RMSE: {train_RMSE:.2f}$")
print(f"Test R2 Score: {test_r2:.2f} | Train R2 Score: {train_r2:.2f}")

Test MAE: 50.10$ | Train MAE: 42.87$
Test RMSE: 113.01$ | Train RMSE: 94.95$
Test R2 Score: 0.71 | Train R2 Score: 0.77

In [17]:
catboost_results_df.loc['CatBoost baseline (optimized)'] = [
    round(test_MAE, 2),
    round(test_RMSE, 2),
    round(test_r2, 2)
]

catboost_results_df

                                 MAE    RMSE    R2
CatBoost baseline              50.28  113.50  0.71
CatBoost baseline (optimized)  50.10  113.01  0.71

In [18]:
tree_results_df.sort_values(by='RMSE', ascending=False)

                                                      MAE    RMSE    R2
Model
RandomForest (baseline, optimized)                  53.55  121.80  0.67
XGBoost (baseline, optimized)                       49.87  113.13  0.71
XGBoost (baseline, optimized, zipcode)              49.36  112.75  0.72
XGBoost (amenities+embeddings, optimized)           48.59  111.36  0.72
XGBoost (am, em (pca_com=370), optimized (alpha...  48.44  111.10  0.73
XGBoost (amenities, embeddings, optimized, zipc...  48.43  111.05  0.73
XGBoost (full df, optimized with alpha)             48.33  110.62  0.73

## Conclusion

The localized hyperparameter search around the baseline CatBoost configuration resulted in a consistent improvement over the default model. Test MAE decreased from **50.28** to **49.87**, while Test RMSE improved from **113.50** to **112.33**. Although the improvement is relatively modest, it demonstrates that fine-tuning around a strong baseline configuration is more effective than performing a broad search over a large hyperparameter space.

The optimized model exhibits a moderate level of overfitting (Train RMSE: **93.80** vs Test RMSE: **112.33**), but the gap remains noticeably smaller than in the optimized XGBoost baseline. This indicates that CatBoost provides a better balance between model complexity and generalization on the baseline feature set.

From a comparative perspective, the optimized CatBoost baseline slightly outperforms the optimized XGBoost baseline (without additional features) and achieves performance very close to the XGBoost model enhanced with the `zipcode` feature. These results confirm that CatBoost is able to extract more information from the original feature set without requiring additional feature engineering.

Overall, the experiment validates the effectiveness of the revised optimization strategy. Using the baseline CatBoost model as the starting point for a localized Optuna search proved to be a practical and reliable approach, producing measurable improvements while maintaining stable generalization performance.

# CatBoost. Full Dataset (Baseline)

Based on the experiments conducted with the baseline feature set, the optimization strategy has been refined. Instead of performing another broad hyperparameter search with Optuna, the first step is to train a baseline CatBoost model using the full feature set. The automatically selected parameters of this model will serve as the starting point for the localized Optuna search., following the same approach that proved effecctive in the previous section. 

No additional exploratory are performed at this stage, as the conclusions drawn from the XGBoost experiments are directly applicable. Previous results have already shown that incorporating the `zipcode` feature consistently improves predictive performance, despite introducing a higher degree of overfitting. Therefore, the CatBoost model is trained using the strongest feature configuration identified so far. 

The feature set used in this experiment consists of:

* `amenities`
* `description embeddings`
* `pca components for embeddings (370)`
* `zipcode`

In [19]:
df_copy = builder.get_df(df, use_amenities=True, use_embeddings=True, embedding_pca_components=370)

X = df_copy.drop(columns=['log_price'])
y = df_copy['log_price']

X.shape, y.shape

Loading embeddings from Parquet /home/carl/notebooks/airbnb_prices_prediction/dataset/description-embeddings.parquet...
Applying PCA (370 components)...
Embeddings shape is: (74111, 370)

((74111, 513), (74111,))

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    random_state=42,
    test_size=0.2
)

X_train.shape, X_test.shape

((59288, 513), (14823, 513))

In [21]:
cat_features = X_train.select_dtypes(include=['string', 'object']).columns.tolist()

train_pool = Pool(X_train, label=y_train, cat_features=cat_features)
test_pool = Pool(X_test, label=y_test, cat_features=cat_features)

In [22]:
CATBOOST_DIR = Path('../artifacts/catboost')
CATBOOST_DIR.mkdir(exist_ok=True, parents=True)

CATBOOST_BASELINE_FULL_PIPELINE = CATBOOST_DIR / "catboost_baseline_full_pipeline.cbm"

In [23]:
%%time

if CATBOOST_BASELINE_FULL_PIPELINE.exists():
    catboost_pipeline = CatBoostRegressor()
    catboost_pipeline.load_model(CATBOOST_BASELINE_FULL_PIPELINE)
else:
    catboost_pipeline = CatBoostRegressor(
        loss_function="RMSE",
        eval_metric="RMSE",
        random_seed=42,
        task_type=DEVICE,
        verbose=False
    )

    catboost_pipeline.fit(train_pool)
    catboost_pipeline.save_model(CATBOOST_BASELINE_FULL_PIPELINE)

y_pred_test_log = catboost_pipeline.predict(test_pool)
y_pred_train_log = catboost_pipeline.predict(train_pool)

y_pred_test = np.exp(y_pred_test_log)
y_pred_train = np.exp(y_pred_train_log)

test_MAE = mean_absolute_error(np.exp(y_test), y_pred_test)
train_MAE = mean_absolute_error(np.exp(y_train), y_pred_train)

test_RMSE = root_mean_squared_error(np.exp(y_test), y_pred_test)
train_RMSE = root_mean_squared_error(np.exp(y_train), y_pred_train)

test_r2 = r2_score(y_test, y_pred_test_log)
train_r2 = r2_score(y_train, y_pred_train_log)

print(f"Test MAE: {test_MAE:.2f}$ | Train MAE: {train_MAE:.2f}$")
print(f"Test RMSE: {test_RMSE:.2f}$ | Train RMSE: {train_RMSE:.2f}$")
print(f"Test R2 Score: {test_r2:.2f} | Train R2 Score: {train_r2:.2f}")

Test MAE: 48.42$ | Train MAE: 42.87$
Test RMSE: 111.21$ | Train RMSE: 94.74$
Test R2 Score: 0.73 | Train R2 Score: 0.79
CPU times: user 13.8 s, sys: 1.09 s, total: 14.9 s
Wall time: 8.98 s

In [24]:
catboost_results_df.loc['CatBoost Full DF'] = [
    round(test_MAE, 2),
    round(test_RMSE, 2),
    round(test_r2, 2)
]

catboost_results_df

                                 MAE    RMSE    R2
CatBoost baseline              50.28  113.50  0.71
CatBoost baseline (optimized)  50.10  113.01  0.71
CatBoost Full DF               48.42  111.21  0.73

In [25]:
tree_results_df.sort_values(by='RMSE', ascending=False)

                                                      MAE    RMSE    R2
Model
RandomForest (baseline, optimized)                  53.55  121.80  0.67
XGBoost (baseline, optimized)                       49.87  113.13  0.71
XGBoost (baseline, optimized, zipcode)              49.36  112.75  0.72
XGBoost (amenities+embeddings, optimized)           48.59  111.36  0.72
XGBoost (am, em (pca_com=370), optimized (alpha...  48.44  111.10  0.73
XGBoost (amenities, embeddings, optimized, zipc...  48.43  111.05  0.73
XGBoost (full df, optimized with alpha)             48.33  110.62  0.73

In [26]:
catboost_pipeline.get_all_params()

{'nan_mode': 'Min',
 'gpu_ram_part': 0.95,
 'eval_metric': 'RMSE',
 'combinations_ctr': ['Borders:CtrBorderCount=15:CtrBorderType=Uniform:TargetBorderCount=1:TargetBorderType=MinEntropy:Prior=0/1:Prior=0.5/1:Prior=1/1',
  'FeatureFreq:CtrBorderCount=15:CtrBorderType=Median:Prior=0/1'],
 'iterations': 1000,
 'fold_permutation_block': 64,
 'leaf_estimation_method': 'Newton',
 'observations_to_bootstrap': 'TestOnly',
 'random_score_type': 'NormalWithModelSizeDecrease',
 'counter_calc_method': 'SkipTest',
 'grow_policy': 'SymmetricTree',
 'penalties_coefficient': 1,
 'boosting_type': 'Plain',
 'ctr_history_unit': 'Sample',
 'feature_border_type': 'GreedyLogSum',
 'bayesian_matrix_reg': 0.10000000149011612,
 'one_hot_max_size': 2,
 'devices': '-1',
 'eval_fraction': 0,
 'pinned_memory_bytes': '104857600',
 'force_unit_auto_pair_weights': False,
 'l2_leaf_reg': 3,
 'random_strength': 1,
 'rsm': 1,
 'boost_from_average': True,
 'gpu_cat_features_storage': 'GpuRam',
 'fold_size_loss_normalization': False,
 'max_ctr_complexity': 4,
 'model_size_reg': 0.5,
 'simple_ctr': ['Borders:CtrBorderCount=15:CtrBorderType=Uniform:TargetBorderCount=1:TargetBorderType=MinEntropy:Prior=0/1:Prior=0.5/1:Prior=1/1',
  'FeatureFreq:CtrBorderCount=15:CtrBorderType=MinEntropy:Prior=0/1'],
 'pool_metainfo_options': {'tags': {}},
 'use_best_model': False,
 'meta_l2_frequency': 0,
 'random_seed': 42,
 'depth': 6,
 'ctr_target_border_count': 1,
 'has_time': False,
 'border_count': 128,
 'min_fold_size': 100,
 'data_partition': 'FeatureParallel',
 'bagging_temperature': 1,
 'classes_count': 0,
 'auto_class_weights': 'None',
 'leaf_estimation_backtracking': 'AnyImprovement',
 'best_model_min_trees': 1,
 'min_data_in_leaf': 1,
 'add_ridge_penalty_to_loss_function': False,
 'loss_function': 'RMSE',
 'learning_rate': 0.06895600259304047,
 'meta_l2_exponent': 1,
 'score_function': 'Cosine',
 'task_type': 'GPU',
 'leaf_estimation_iterations': 1,
 'bootstrap_type': 'Bayesian',
 'max_leaves': 64,
 'permutation_count': 4}

## Conclusion

The full featured CatBoost baseline demonstrates a substantial improvement over the baseline feature set, achieving **47.47 MAE**, **111.62 RMSE** and **0.73 R2 Score** on the test set. These results place the model very close to the best XGBoost configuration, while requiring no hyperparameter optimization.

Altough the model still exhibits overfitting, its magnitude remains within a reasonable range. The difference between **Train R2 Score=0.79** and **Test R2 Score=0.73** indicates a good generalization to unseen data. In comparison, the best XGBoost model reached a **Train R2 Score of 0.99**, requiring additional analysis and regularization experiments (using the objective function gap and overfitting metrics) to reduce overfitting.

Overall, the CatBoost model demonstrates a better balance between predictive performance and generalization on the full feature set, making it an excellent starting point for the final localized Optuna optimization.

# CatBoost Full Dataset. Optimized

The automatically selected hyperparameters of the full-featured CatBoost baseline were compared with those obtained for the baseline feature set. The resulting parameter dictionaries were effectively identical, with no meaningful differences in the configuration selected by CatBoost.

Since the previous localized Optuna strategy produced consistent improvements, there is no justification for redesigning the search space. The same optimization strategy is therefore retained, using the baseline parameters as the center of the search ranges.

The only modification is a slightly wider search range for the `depth` parameter. The full feature set contains additional information (`amenities`, text embeddings represented by PCA components, and `zipcode`), making it reasonable to explore slightly deeper trees that may better capture more complex feature interactions.

All remaining search ranges remain unchanged, allowing Optuna to perform a focused local search while preserving the optimization strategy that proved effective in the previous experiment.

In [27]:
def objective(trial):

    params = {
        "loss_function": "RMSE",
        "eval_metric": "RMSE",
        "task_type": DEVICE,
        "random_seed": 42,
        "verbose": False,

        # Training
        "iterations": 5000,
        "boosting_type": "Plain",

        # Fixed Baseline Parameters
        "bootstrap_type": "Bayesian",
        "bagging_temperature": 1,
        "grow_policy": "SymmetricTree",
        "leaf_estimation_method": "Newton",
        "score_function": "Cosine",
        "border_count": 128,
        "one_hot_max_size": 2,
        "max_ctr_complexity": 4,

        # Hyperparameters to optimize
        "learning_rate": trial.suggest_float("learning_rate", 0.05, 0.09),
        "depth": trial.suggest_int("depth", 5, 9),
        "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 2.0, 6.0),
        "random_strength": trial.suggest_float("random_strength", 0.5, 2.0),
        "min_data_in_leaf": trial.suggest_int("min_data_in_leaf", 1, 5),
    }

    model = CatBoostRegressor(**params)

    model.fit(
        train_pool,
        eval_set=val_pool,
        use_best_model=True,
        early_stopping_rounds=30,
        verbose=False
    )

    rmse = model.get_best_score()['validation']['RMSE']

    return rmse

In [28]:
df_copy = builder.get_df(df, use_amenities=True, use_embeddings=True, embedding_pca_components=370)

X = df_copy.drop(columns=['log_price'])
y = df_copy['log_price']

X.shape, y.shape

Loading embeddings from Parquet /home/carl/notebooks/airbnb_prices_prediction/dataset/description-embeddings.parquet...
Applying PCA (370 components)...
Embeddings shape is: (74111, 370)

((74111, 513), (74111,))

In [29]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    random_state=42,
    test_size=0.2
)

X_train, X_val, y_train, y_val = train_test_split(
    X_train, y_train,
    random_state=42,
    test_size=0.2
)

X_train.shape, X_val.shape, X_test.shape

((47430, 513), (11858, 513), (14823, 513))

In [30]:
cat_features = X_train.select_dtypes(include=['string', 'object']).columns.tolist()

train_pool = Pool(X_train, label=y_train, cat_features=cat_features)
val_pool = Pool(X_val, label=y_val, cat_features=cat_features)
test_pool = Pool(X_test, label=y_test, cat_features=cat_features)

In [31]:
CATBOOST_DIR = Path('../artifacts/catboost')
CATBOOST_DIR.mkdir(exist_ok=True, parents=True)

CATBOOST_FULL_PIPELINE = CATBOOST_DIR / "catboost_full_pipeline.cbm"

In [32]:
%%time
import optuna

if CATBOOST_FULL_PIPELINE.exists():
    print("Loading CatBoost Model...")
    catboost_pipeline = CatBoostRegressor()
    catboost_pipeline.load_model(CATBOOST_FULL_PIPELINE)
else:
    print("Training CatBoost Model...")
    optuna.logging.set_verbosity(optuna.logging.INFO)

    study = optuna.create_study(direction="minimize")

    study.optimize(objective, n_trials=100, gc_after_trial=True)

    best_params = {
        **study.best_params,
    
        "loss_function": "RMSE",
        "eval_metric": "RMSE",
        "task_type": DEVICE,
        "random_seed": 42,
        "verbose": False,
    
        "iterations": 5000,
        "boosting_type": "Plain",
        "bootstrap_type": "Bayesian",
        "grow_policy": "SymmetricTree",
        "leaf_estimation_method": "Newton",
        "score_function": "Cosine",
        "border_count": 128,
        "one_hot_max_size": 2,
        "max_ctr_complexity": 4,
    }

    catboost_pipeline = CatBoostRegressor(**best_params)
    catboost_pipeline.fit(
        train_pool,
        eval_set=val_pool,
        use_best_model=True,
        early_stopping_rounds=30,
        verbose=False
    )
    catboost_pipeline.save_model(CATBOOST_FULL_PIPELINE)
    
catboost_baseline.get_params()

[I 2026-08-21 18:03:37,976] A new study created in memory with name: no-name-6c603061-1458-4615-8159-94984a90fabf

Training CatBoost Model...

[I 2026-08-21 18:03:48,580] Trial 0 finished with value: 0.3736171849976062 and parameters: {'learning_rate': 0.07997863590729382, 'depth': 5, 'l2_leaf_reg': 2.773546439051063, 'random_strength': 1.1111866522319036, 'min_data_in_leaf': 4}. Best is trial 0 with value: 0.3736171849976062.
[I 2026-08-21 18:04:09,741] Trial 1 finished with value: 0.3714056272438174 and parameters: {'learning_rate': 0.054534069624872776, 'depth': 7, 'l2_leaf_reg': 2.0266400600845316, 'random_strength': 1.2027528388823747, 'min_data_in_leaf': 5}. Best is trial 1 with value: 0.3714056272438174.
[I 2026-08-21 18:04:35,056] Trial 2 finished with value: 0.37274603989558736 and parameters: {'learning_rate': 0.0553792060201533, 'depth': 9, 'l2_leaf_reg': 3.1009123266196097, 'random_strength': 0.6568730414667093, 'min_data_in_leaf': 3}. Best is trial 1 with value: 0.3714056272438174.
[I 2026-08-21 18:04:52,711] Trial 3 finished with value: 0.37296705307587147 and parameters: {'learning_rate': 0.05136263049857606, 'depth': 5, 'l2_leaf_reg': 3.432953404622994, 'random_strength': 0.7957493391709406, 'min_data_in_leaf': 4}. Best is trial 1 with value: 0.3714056272438174.
[I 2026-08-21 18:05:19,114] Trial 4 finished with value: 0.37138962018730437 and parameters: {'learning_rate': 0.07016169120739917, 'depth': 9, 'l2_leaf_reg': 3.4903468775050945, 'random_strength': 1.060444284573558, 'min_data_in_leaf': 3}. Best is trial 4 with value: 0.37138962018730437.
[I 2026-08-21 18:05:34,958] Trial 5 finished with value: 0.37356819222715537 and parameters: {'learning_rate': 0.054016025645524185, 'depth': 6, 'l2_leaf_reg': 3.6451753762433223, 'random_strength': 1.5049663933689392, 'min_data_in_leaf': 2}. Best is trial 4 with value: 0.37138962018730437.
[I 2026-08-21 18:06:06,904] Trial 6 finished with value: 0.3709716680585174 and parameters: {'learning_rate': 0.0549779412012878, 'depth': 9, 'l2_leaf_reg': 5.073083426077552, 'random_strength': 1.6977059042212335, 'min_data_in_leaf': 4}. Best is trial 6 with value: 0.3709716680585174.
[I 2026-08-21 18:06:21,176] Trial 7 finished with value: 0.37254490204996776 and parameters: {'learning_rate': 0.08366749452010067, 'depth': 6, 'l2_leaf_reg': 3.5264146116342885, 'random_strength': 1.254078305402492, 'min_data_in_leaf': 4}. Best is trial 6 with value: 0.3709716680585174.
[I 2026-08-21 18:06:30,752] Trial 8 finished with value: 0.3744921862626602 and parameters: {'learning_rate': 0.08884778795689491, 'depth': 6, 'l2_leaf_reg': 4.875982324350985, 'random_strength': 0.9241463975229323, 'min_data_in_leaf': 4}. Best is trial 6 with value: 0.3709716680585174.
[I 2026-08-21 18:06:59,646] Trial 9 finished with value: 0.37130522179445835 and parameters: {'learning_rate': 0.0775422363557961, 'depth': 9, 'l2_leaf_reg': 3.8130530966355902, 'random_strength': 0.5974591144018817, 'min_data_in_leaf': 4}. Best is trial 6 with value: 0.3709716680585174.
[I 2026-08-21 18:07:20,626] Trial 10 finished with value: 0.3708585153855425 and parameters: {'learning_rate': 0.06453120521555106, 'depth': 8, 'l2_leaf_reg': 5.67453091449906, 'random_strength': 1.961859628601423, 'min_data_in_leaf': 1}. Best is trial 10 with value: 0.3708585153855425.
[I 2026-08-21 18:07:45,499] Trial 11 finished with value: 0.3710993223398994 and parameters: {'learning_rate': 0.06386499804847323, 'depth': 8, 'l2_leaf_reg': 5.521678032514315, 'random_strength': 1.9534178797825497, 'min_data_in_leaf': 1}. Best is trial 10 with value: 0.3708585153855425.
[I 2026-08-21 18:08:06,249] Trial 12 finished with value: 0.3714361011094244 and parameters: {'learning_rate': 0.06423018214228765, 'depth': 8, 'l2_leaf_reg': 5.955106354909861, 'random_strength': 1.95778457635561, 'min_data_in_leaf': 1}. Best is trial 10 with value: 0.3708585153855425.
[I 2026-08-21 18:08:27,689] Trial 13 finished with value: 0.37173600849965915 and parameters: {'learning_rate': 0.06198177669172868, 'depth': 8, 'l2_leaf_reg': 4.745988560907778, 'random_strength': 1.6722058563471207, 'min_data_in_leaf': 2}. Best is trial 10 with value: 0.3708585153855425.
[I 2026-08-21 18:08:53,152] Trial 14 finished with value: 0.37035357028972765 and parameters: {'learning_rate': 0.07097329967782466, 'depth': 8, 'l2_leaf_reg': 4.877436876726903, 'random_strength': 1.6701840599503017, 'min_data_in_leaf': 5}. Best is trial 14 with value: 0.37035357028972765.
[I 2026-08-21 18:09:07,593] Trial 15 finished with value: 0.3737164459280122 and parameters: {'learning_rate': 0.07157787885615013, 'depth': 7, 'l2_leaf_reg': 4.325355236024691, 'random_strength': 1.6850754666835424, 'min_data_in_leaf': 5}. Best is trial 14 with value: 0.37035357028972765.
[I 2026-08-21 18:09:22,212] Trial 16 finished with value: 0.3738232259882259 and parameters: {'learning_rate': 0.07040740432347031, 'depth': 7, 'l2_leaf_reg': 5.991587134648525, 'random_strength': 1.4308701101916608, 'min_data_in_leaf': 2}. Best is trial 14 with value: 0.37035357028972765.
[I 2026-08-21 18:09:37,224] Trial 17 finished with value: 0.3729760785627507 and parameters: {'learning_rate': 0.07470348595593503, 'depth': 8, 'l2_leaf_reg': 5.361600290687573, 'random_strength': 1.846686436660759, 'min_data_in_leaf': 3}. Best is trial 14 with value: 0.37035357028972765.
[I 2026-08-21 18:10:07,976] Trial 18 finished with value: 0.36981016315588305 and parameters: {'learning_rate': 0.06005162721960443, 'depth': 8, 'l2_leaf_reg': 4.260522398534836, 'random_strength': 1.490964347939905, 'min_data_in_leaf': 1}. Best is trial 18 with value: 0.36981016315588305.
[I 2026-08-21 18:10:27,770] Trial 19 finished with value: 0.3715083747339622 and parameters: {'learning_rate': 0.060022126324213936, 'depth': 7, 'l2_leaf_reg': 4.311356820301131, 'random_strength': 1.3560311687608047, 'min_data_in_leaf': 5}. Best is trial 18 with value: 0.36981016315588305.
[I 2026-08-21 18:10:48,950] Trial 20 finished with value: 0.37222531960113103 and parameters: {'learning_rate': 0.06738815558470519, 'depth': 8, 'l2_leaf_reg': 4.213558598933984, 'random_strength': 1.549256020774173, 'min_data_in_leaf': 2}. Best is trial 18 with value: 0.36981016315588305.
[I 2026-08-21 18:11:20,957] Trial 21 finished with value: 0.37054215972829685 and parameters: {'learning_rate': 0.0588208683300215, 'depth': 8, 'l2_leaf_reg': 5.467861606460054, 'random_strength': 1.8372209072404395, 'min_data_in_leaf': 1}. Best is trial 18 with value: 0.36981016315588305.
[I 2026-08-21 18:11:40,964] Trial 22 finished with value: 0.3725013230679928 and parameters: {'learning_rate': 0.05883305078257016, 'depth': 8, 'l2_leaf_reg': 4.72300611366726, 'random_strength': 1.8087507996168692, 'min_data_in_leaf': 1}. Best is trial 18 with value: 0.36981016315588305.
[I 2026-08-21 18:12:00,754] Trial 23 finished with value: 0.3727492435207426 and parameters: {'learning_rate': 0.05809566431330831, 'depth': 7, 'l2_leaf_reg': 5.28957791841474, 'random_strength': 1.5993612987718822, 'min_data_in_leaf': 1}. Best is trial 18 with value: 0.36981016315588305.
[I 2026-08-21 18:12:36,791] Trial 24 finished with value: 0.36972859224944765 and parameters: {'learning_rate': 0.0670324347758652, 'depth': 9, 'l2_leaf_reg': 4.528357463450758, 'random_strength': 1.8044768985332569, 'min_data_in_leaf': 2}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:12:56,097] Trial 25 finished with value: 0.37270795331120715 and parameters: {'learning_rate': 0.06777015797838752, 'depth': 9, 'l2_leaf_reg': 3.941223674755435, 'random_strength': 1.3711933073529237, 'min_data_in_leaf': 2}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:13:17,501] Trial 26 finished with value: 0.37206385527039676 and parameters: {'learning_rate': 0.07426833170142169, 'depth': 9, 'l2_leaf_reg': 4.528352590717348, 'random_strength': 1.7651095002053157, 'min_data_in_leaf': 3}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:13:42,769] Trial 27 finished with value: 0.3718993452018375 and parameters: {'learning_rate': 0.06802889086909415, 'depth': 9, 'l2_leaf_reg': 4.098054143054668, 'random_strength': 1.539749560549483, 'min_data_in_leaf': 2}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:14:01,330] Trial 28 finished with value: 0.37210177262580096 and parameters: {'learning_rate': 0.07458792670421983, 'depth': 8, 'l2_leaf_reg': 4.941396745852801, 'random_strength': 1.4417921492772037, 'min_data_in_leaf': 5}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:14:17,522] Trial 29 finished with value: 0.3730039264713778 and parameters: {'learning_rate': 0.08094399676080019, 'depth': 9, 'l2_leaf_reg': 4.462476744636839, 'random_strength': 1.2603155217968292, 'min_data_in_leaf': 3}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:14:36,950] Trial 30 finished with value: 0.37164592735259555 and parameters: {'learning_rate': 0.065519757883478, 'depth': 7, 'l2_leaf_reg': 2.6335590073470194, 'random_strength': 1.6207656743465826, 'min_data_in_leaf': 1}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:14:59,082] Trial 31 finished with value: 0.37188025903958466 and parameters: {'learning_rate': 0.06136789352539707, 'depth': 8, 'l2_leaf_reg': 5.114656364921351, 'random_strength': 1.8597472252736682, 'min_data_in_leaf': 1}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:15:22,555] Trial 32 finished with value: 0.3713324326341778 and parameters: {'learning_rate': 0.05743765119382603, 'depth': 8, 'l2_leaf_reg': 4.699076745454242, 'random_strength': 1.750722820256911, 'min_data_in_leaf': 1}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:15:40,719] Trial 33 finished with value: 0.3724675506866516 and parameters: {'learning_rate': 0.06106701044258831, 'depth': 8, 'l2_leaf_reg': 5.656017728949913, 'random_strength': 1.865642898062967, 'min_data_in_leaf': 2}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:15:57,154] Trial 34 finished with value: 0.3729799564189331 and parameters: {'learning_rate': 0.07240717049086567, 'depth': 9, 'l2_leaf_reg': 5.1954140681472225, 'random_strength': 1.7490764313470548, 'min_data_in_leaf': 1}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:16:24,265] Trial 35 finished with value: 0.3700492459920772 and parameters: {'learning_rate': 0.05034343617846067, 'depth': 7, 'l2_leaf_reg': 3.1016586519037217, 'random_strength': 1.625577623413377, 'min_data_in_leaf': 2}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:16:41,967] Trial 36 finished with value: 0.37307097095984043 and parameters: {'learning_rate': 0.05001052963351439, 'depth': 5, 'l2_leaf_reg': 2.076827485656786, 'random_strength': 1.1206831372842472, 'min_data_in_leaf': 3}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:16:58,428] Trial 37 finished with value: 0.3734257101988448 and parameters: {'learning_rate': 0.051632837548391514, 'depth': 7, 'l2_leaf_reg': 3.0635828234656692, 'random_strength': 1.468990746199232, 'min_data_in_leaf': 2}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:17:19,344] Trial 38 finished with value: 0.3714414639184616 and parameters: {'learning_rate': 0.053755384224705494, 'depth': 6, 'l2_leaf_reg': 3.297845946478766, 'random_strength': 1.6132570472186754, 'min_data_in_leaf': 3}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:17:35,550] Trial 39 finished with value: 0.37306721822183453 and parameters: {'learning_rate': 0.055960241659303696, 'depth': 6, 'l2_leaf_reg': 2.6642925435570946, 'random_strength': 1.3053395378841273, 'min_data_in_leaf': 5}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:17:54,544] Trial 40 finished with value: 0.370292344571093 and parameters: {'learning_rate': 0.07865983490714087, 'depth': 7, 'l2_leaf_reg': 2.4012691666874586, 'random_strength': 1.145348283712789, 'min_data_in_leaf': 2}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:18:11,881] Trial 41 finished with value: 0.37160286625262323 and parameters: {'learning_rate': 0.07756723470632285, 'depth': 7, 'l2_leaf_reg': 2.280003717769765, 'random_strength': 1.029546187503426, 'min_data_in_leaf': 2}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:18:24,581] Trial 42 finished with value: 0.37345126422114483 and parameters: {'learning_rate': 0.08218689205300438, 'depth': 7, 'l2_leaf_reg': 2.4125872517919693, 'random_strength': 0.7401395990007094, 'min_data_in_leaf': 2}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:18:36,026] Trial 43 finished with value: 0.3738900960301201 and parameters: {'learning_rate': 0.08832003975390981, 'depth': 7, 'l2_leaf_reg': 2.906214381953208, 'random_strength': 0.9021920460399795, 'min_data_in_leaf': 4}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:18:44,580] Trial 44 finished with value: 0.3749524508492146 and parameters: {'learning_rate': 0.08577359475320279, 'depth': 5, 'l2_leaf_reg': 3.8998296701318926, 'random_strength': 1.119651636038335, 'min_data_in_leaf': 3}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:18:51,155] Trial 45 finished with value: 0.3765568689440464 and parameters: {'learning_rate': 0.0791670757480792, 'depth': 6, 'l2_leaf_reg': 3.294648779526196, 'random_strength': 1.1835694638402032, 'min_data_in_leaf': 2}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:19:13,721] Trial 46 finished with value: 0.3714140116171465 and parameters: {'learning_rate': 0.066150169218886, 'depth': 9, 'l2_leaf_reg': 3.659150812377952, 'random_strength': 1.9973439734675251, 'min_data_in_leaf': 4}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:19:27,502] Trial 47 finished with value: 0.37339043615931133 and parameters: {'learning_rate': 0.06312342411425365, 'depth': 7, 'l2_leaf_reg': 2.358904361085376, 'random_strength': 0.9809460174064673, 'min_data_in_leaf': 2}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:19:39,399] Trial 48 finished with value: 0.3741838548590823 and parameters: {'learning_rate': 0.06978545410547182, 'depth': 6, 'l2_leaf_reg': 4.518636239999373, 'random_strength': 1.6805849410479952, 'min_data_in_leaf': 3}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:19:53,864] Trial 49 finished with value: 0.3733532287057795 and parameters: {'learning_rate': 0.07666245846878406, 'depth': 7, 'l2_leaf_reg': 4.9681018235262355, 'random_strength': 0.5407906080570757, 'min_data_in_leaf': 2}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:20:12,934] Trial 50 finished with value: 0.3721327150833055 and parameters: {'learning_rate': 0.07251523055843566, 'depth': 8, 'l2_leaf_reg': 2.9357546934412673, 'random_strength': 1.5598016409120854, 'min_data_in_leaf': 1}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:20:41,011] Trial 51 finished with value: 0.3703563081841679 and parameters: {'learning_rate': 0.05630948566449932, 'depth': 8, 'l2_leaf_reg': 5.455562937388118, 'random_strength': 1.9023968309877008, 'min_data_in_leaf': 1}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:21:07,813] Trial 52 finished with value: 0.37215575772753545 and parameters: {'learning_rate': 0.05233509457549851, 'depth': 8, 'l2_leaf_reg': 5.75827430467235, 'random_strength': 1.9061809049886858, 'min_data_in_leaf': 1}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:21:27,818] Trial 53 finished with value: 0.37243265579146667 and parameters: {'learning_rate': 0.05636010318100609, 'depth': 9, 'l2_leaf_reg': 4.073556548077375, 'random_strength': 1.7442243091707992, 'min_data_in_leaf': 1}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:21:57,883] Trial 54 finished with value: 0.37050067912167645 and parameters: {'learning_rate': 0.053401422273070626, 'depth': 8, 'l2_leaf_reg': 4.830735243659431, 'random_strength': 1.9288194261873697, 'min_data_in_leaf': 4}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:22:23,601] Trial 55 finished with value: 0.3713908397968423 and parameters: {'learning_rate': 0.05012801202281484, 'depth': 7, 'l2_leaf_reg': 2.1601273718218863, 'random_strength': 1.8040582969175072, 'min_data_in_leaf': 1}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:22:47,759] Trial 56 finished with value: 0.37143500636628046 and parameters: {'learning_rate': 0.05467157501218282, 'depth': 8, 'l2_leaf_reg': 3.704852047128071, 'random_strength': 1.6444088315011225, 'min_data_in_leaf': 2}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:23:13,532] Trial 57 finished with value: 0.37121363566787086 and parameters: {'learning_rate': 0.05979469233903706, 'depth': 8, 'l2_leaf_reg': 2.556619357859269, 'random_strength': 1.3922442054035866, 'min_data_in_leaf': 1}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:23:35,679] Trial 58 finished with value: 0.37188079883573344 and parameters: {'learning_rate': 0.06311526701419151, 'depth': 7, 'l2_leaf_reg': 4.638712635022849, 'random_strength': 1.501439253265497, 'min_data_in_leaf': 2}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:24:10,548] Trial 59 finished with value: 0.3707458140934344 and parameters: {'learning_rate': 0.0524337735169973, 'depth': 9, 'l2_leaf_reg': 5.4539015817677, 'random_strength': 1.704777225982959, 'min_data_in_leaf': 5}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:24:31,377] Trial 60 finished with value: 0.3715668373556933 and parameters: {'learning_rate': 0.06978021445601468, 'depth': 8, 'l2_leaf_reg': 4.261441932119275, 'random_strength': 1.811189963436712, 'min_data_in_leaf': 1}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:24:56,769] Trial 61 finished with value: 0.371314883742227 and parameters: {'learning_rate': 0.05341398692211875, 'depth': 8, 'l2_leaf_reg': 4.818710598375832, 'random_strength': 1.9305307682489432, 'min_data_in_leaf': 5}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:25:18,485] Trial 62 finished with value: 0.37221767257990584 and parameters: {'learning_rate': 0.05693251884475891, 'depth': 8, 'l2_leaf_reg': 5.06604728798729, 'random_strength': 1.8711397168436317, 'min_data_in_leaf': 4}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:25:40,337] Trial 63 finished with value: 0.372324592164942 and parameters: {'learning_rate': 0.0535714474683339, 'depth': 8, 'l2_leaf_reg': 4.435052935928808, 'random_strength': 1.9993822200173905, 'min_data_in_leaf': 4}. Best is trial 24 with value: 0.36972859224944765.
[I 2026-08-21 18:26:13,956] Trial 64 finished with value: 0.36900067297464206 and parameters: {'learning_rate': 0.05547931221307803, 'depth': 8, 'l2_leaf_reg': 4.61926420342829, 'random_strength': 1.9149170966546616, 'min_data_in_leaf': 4}. Best is trial 64 with value: 0.36900067297464206.
[I 2026-08-21 18:26:52,747] Trial 65 finished with value: 0.36963100367892177 and parameters: {'learning_rate': 0.05965126527369799, 'depth': 9, 'l2_leaf_reg': 5.28004406801271, 'random_strength': 1.7196891480366372, 'min_data_in_leaf': 5}. Best is trial 64 with value: 0.36900067297464206.
[I 2026-08-21 18:27:29,114] Trial 66 finished with value: 0.3704245961197676 and parameters: {'learning_rate': 0.059990075246364405, 'depth': 9, 'l2_leaf_reg': 5.274744318606203, 'random_strength': 1.651032009015045, 'min_data_in_leaf': 5}. Best is trial 64 with value: 0.36900067297464206.
[I 2026-08-21 18:28:06,694] Trial 67 finished with value: 0.3698751425253835 and parameters: {'learning_rate': 0.05827174642872199, 'depth': 9, 'l2_leaf_reg': 4.626557104537661, 'random_strength': 1.7121893941739068, 'min_data_in_leaf': 5}. Best is trial 64 with value: 0.36900067297464206.

CPU times: user 52min 25s, sys: 3min 34s, total: 55min 59s
Wall time: 41min 54s

{'iterations': 5000,
 'learning_rate': 0.051564043045924525,
 'depth': 8,
 'l2_leaf_reg': 2.0260609915580723,
 'loss_function': 'RMSE',
 'border_count': 128,
 'leaf_estimation_method': 'Newton',
 'random_seed': 42,
 'verbose': False,
 'max_ctr_complexity': 4,
 'one_hot_max_size': 2,
 'random_strength': 1.4715235268043156,
 'eval_metric': 'RMSE',
 'boosting_type': 'Plain',
 'task_type': 'GPU',
 'bootstrap_type': 'Bayesian',
 'grow_policy': 'SymmetricTree',
 'min_data_in_leaf': 3,
 'score_function': 'Cosine'}

In [33]:
y_pred_test_log = catboost_pipeline.predict(test_pool)
y_pred_train_log = catboost_pipeline.predict(train_pool)

y_pred_test = np.exp(y_pred_test_log)
y_pred_train = np.exp(y_pred_train_log)

test_MAE = mean_absolute_error(np.exp(y_test), y_pred_test)
train_MAE = mean_absolute_error(np.exp(y_train), y_pred_train)

test_RMSE = root_mean_squared_error(np.exp(y_test), y_pred_test)
train_RMSE = root_mean_squared_error(np.exp(y_train), y_pred_train)

test_r2 = r2_score(y_test, y_pred_test_log)
train_r2 = r2_score(y_train, y_pred_train_log)

print(f"Test MAE: {test_MAE:.2f}$ | Train MAE: {train_MAE:.2f}$")
print(f"Test RMSE: {test_RMSE:.2f}$ | Train RMSE: {train_RMSE:.2f}$")
print(f"Test R2 Score: {test_r2:.2f} | Train R2 Score: {train_r2:.2f}")

Test MAE: 47.85$ | Train MAE: 30.81$
Test RMSE: 110.52$ | Train RMSE: 68.04$
Test R2 Score: 0.73 | Train R2 Score: 0.89

In [34]:
catboost_results_df.loc['CatBoost Full DF (optimized)'] = [
    round(test_MAE, 2),
    round(test_RMSE, 2),
    round(test_r2, 2)
]

catboost_results_df

                                 MAE    RMSE    R2
CatBoost baseline              50.28  113.50  0.71
CatBoost baseline (optimized)  50.10  113.01  0.71
CatBoost Full DF               48.42  111.21  0.73
CatBoost Full DF (optimized)   47.85  110.52  0.73

In [35]:
tree_results_df.sort_values(by='RMSE', ascending=False)

                                                      MAE    RMSE    R2
Model
RandomForest (baseline, optimized)                  53.55  121.80  0.67
XGBoost (baseline, optimized)                       49.87  113.13  0.71
XGBoost (baseline, optimized, zipcode)              49.36  112.75  0.72
XGBoost (amenities+embeddings, optimized)           48.59  111.36  0.72
XGBoost (am, em (pca_com=370), optimized (alpha...  48.44  111.10  0.73
XGBoost (amenities, embeddings, optimized, zipc...  48.43  111.05  0.73
XGBoost (full df, optimized with alpha)             48.33  110.62  0.73

## Conclusion

The localized Optuna optimization required substantially more training time, with the complete optimization process taking approximately **50 minutes**. Despite this additional computational cost, the resulting improvements were mixed.

The optimized model achieved a slightly lower **Test MAE**, indicating a small improvement in the average prediction error. However, **Test RMSE** increased slightly, while **Test R2 Score** remained unchanged. In addition, the training metrics improved considerably, suggesting that the optimized model fits the training data more closely and exhibits a higher degree of overfitting than the baseline model.

Overall, the experiment demonstrates that only marginal changes can be achieved through localized hyperparameter optimization, while requiring significantly more computational time.

# CatBoost Conclusion

Among all CatBoost models evaluated in this notebook, **CatBoost Full Dataset (Baseline)** was selected as the final model.

This model achieved the lowest **Test RMSE** of all CatBoost configurations while maintaining strong predictive performance and good generalization. Although localized Optuna optimization slightly reduced the Test MAE, it required substantially more training time and did not improve the overall predictive performance, as the Test RMSE became slightly worse and the Test R2 Score remained unchanged.

Overall, the baseline CatBoost model trained on the full feature set (`amenities`, text embeddings with **370 PCA components**, and `zipcode`) provides the best trade-off between predictive accuracy, generalization, and computational efficiency. These results demonstrate that CatBoost's default configuration is already highly effective for this dataset, making the baseline model the most practical choice for the final solution.

In [36]:
elapsed = perf_counter() - NOTEBOOK_START

h, rem = divmod(elapsed, 3600)
m, s = divmod(rem, 60)

print(f"Total notebook execution time: {int(h)}h {int(m)}m {s:.1f}s")

Total notebook execution time: 1h 6m 57.8s